binary_sensor:
 - platform: 'bayesian'
    prior: 0.75
    name: 'jhh Home'
    probability_threshold: 0.95
    observations:
      - entity_id: 'device_tracker.pi_rashmiphone'
        prob_given_true: 0.8
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.rashmiappiphone'
        prob_given_true: 0.99
        prob_given_false: 0.10
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.rashmisiphone'
        prob_given_true: 0.99
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.sonu_sonu'
        prob_given_true: 1
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.e1594e5321df414c82daf655d5282fca'
        prob_given_true: 0.99
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
  - platform: 'bayesian'
    prior: 0.25
    name: 'Alok Home'
    probability_threshold: 0.95
    observations:
      - entity_id: 'device_tracker.pi_alokphone'
        prob_given_true: 0.8
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.alokiosiphone'
        prob_given_true: 0.99
        prob_given_false: 0.10
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.myiphone'
        prob_given_true: 0.99
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.alok_alok'
        prob_given_true: 0.99
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.b4445761f6c04b7f835fcfdc03b47111'
        prob_given_true: 0.99
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
