homeassistant:
  customize:
    sensor.filtered_bedroom_bt_distance:
      friendly_name: 离房间蓝牙距离
      icon: mdi:map-marker-distance
    sensor.filtered_washroom_bt_distance:
      friendly_name: 离厕所蓝牙距离
      icon: mdi:map-marker-distance
    sensor.filtered_kitchen_bt_distance:
      friendly_name: 离厨房蓝牙距离
      icon: mdi:map-marker-distance
    sensor.filtered_guestroom BT distance:
      friendly_name: 离客房蓝牙距离
      icon: mdi:map-marker-distance

sensor:
  - platform: mqtt
    name: "bedroom BT distance"
    state_topic: "home/BTtoMQTT/room2/房间"
    unit_of_measurement: 'm'
    value_template: "{{ value_json.distance }}"
  - platform: mqtt
    name: "washroom BT distance"
    state_topic: "home/BTtoMQTT/room2/厕所"
    unit_of_measurement: 'm'
    value_template: "{{ value_json.distance }}"
  - platform: mqtt
    name: "kitchen BT distance"
    state_topic: "home/BTtoMQTT/room2/厨房"
    unit_of_measurement: 'm'
    value_template: "{{ value_json.distance }}"
  - platform: mqtt
    name: "guestroom BT distance"
    state_topic: "home/BTtoMQTT/room2/客房"
    unit_of_measurement: 'm'
    value_template: "{{ value_json.distance }}"
  - platform: filter
    name: "filtered bedroom BT distance"
    entity_id: sensor.bedroom_bt_distance
    filters:
      - filter: outlier
        window_size: 2
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2
  - platform: filter
    name: "filtered washroom BT distance"
    entity_id: sensor.washroom_bt_distance
    filters:
      - filter: outlier
        window_size: 2
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2
  - platform: filter
    name: "filtered kitchen BT distance"
    entity_id: sensor.kitchen_bt_distance
    filters:
      - filter: outlier
        window_size: 2
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2
  - platform: filter
    name: "filtered guestroom BT distance"
    entity_id: sensor.guestroom_bt_distance
    filters:
      - filter: outlier
        window_size: 2
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2
