##########################################################
#          用门磁和人体感应判断进门还是出门并tts问候        #
##########################################################
homeassistant:
binary_sensor:
  - platform: mqtt
    name: "CF Body Motion"
    state_topic: "home/CF/HCSR501toMQTT"
    qos: 0
    payload_on: "true"
    payload_off: "false"
    device_class: motion
        
automation:
- alias: notify to close the door
  trigger:
    platform: state
    entity_id: binary_sensor.menci
    to: 'on'
    for:
      minutes: 30
      seconds: 00
  condition:
    condition: template
    value_template: '{{(as_timestamp(now()) - as_timestamp(states.binary_sensor.cf_body_motion.last_changed))|int > 1800}}'
#    value_template: '{{((as_timestamp(now()) - as_timestamp(states.sensor.jhh.last_changed))|int <60)}}'
  action:
    service: notify.notify
    data_template:
      message: >
        {{ [
        "请关门",
        "门开着，会有蚊子苍蝇飞进来哦"
        ] | random }}
- alias: welcome home
  trigger:
    platform: state
    entity_id: binary_sensor.cf_body_motion
    to: 'on'
  condition:
    condition: template
    value_template: '{{(as_timestamp(now()) - as_timestamp(states.binary_sensor.menci.last_changed)) |int <5}}'
#    value_template: '{{((as_timestamp(now()) - as_timestamp(states.sensor.jhh.last_changed))|int <60)}}'
  action:
    - service: notify.weixin
      data_template:
        message: "{{ now().strftime(\"%H:%M\") }}时，有人回家"
        title: "门磁提醒"
    - service: notify.notify
      data_template:
        message: >
          {% set timenow = now().time().strftime("%H") | int %}
          {% if timenow > 6 and timenow < 12 %}
          早上好
          {% elif timenow >= 12 and timenow < 14 %}
          中午好
          {% elif timenow >= 14 and timenow < 18 %}
          下午好
          {% elif timenow >= 18 and timenow < 23 %}
          晚上好
          {% else %}
          你好
          {% endif %}
          {{ [
          "欢迎回家",
          "现在是{{ now().strftime(\"%H:%M\") }},家里的温度是{{ states.sensor.gateway_temp.state }}度,相对湿度是百分之{{ states.sensor.gateway_hum.state }}",
          "想家了吗?莉莎已经一天没有见到你啦，和它打个招呼吧",
          "金屋银屋不如自己的狗窝,还是家里最舒服"
          ] | random }}
         
    - service: camera.snapshot
      data:
        entity_id: camera.ezviz
        filename: '/data/data/com.termux/files/home/.homeassistant/downloads/ezviz.jpg'
    - service: notify.mypushbullet
      data:
        title: "有人开门"
        message: "{{ now().strftime(\"%H:%M\") }}时，有人开门,See attached picture"
        #        target:
        #          - "device/OPPO"
        #          - 'email/346771457@qq.com'
        #          - 'email/652612825@qq.com'                                        
        data:
          file: /data/data/com.termux/files/home/.homeassistant/downloads/ezviz.jpg    
- alias: go out
  trigger:
    platform: state
    entity_id: binary_sensor.menci
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.cf_body_motion
    state: 'on'
#    value_template: '{{((as_timestamp(now()) - as_timestamp(states.sensor.jhh.last_changed))|int <60)}}'
  action:
    - service: script.turn_on
      entity_id: script.download_caiyundata
    - service: notify.notify
      data_template:
        message: >
          {% set timenow = now().time().strftime("%H") | int %}
          {% if timenow > 6 and timenow < 12 %}
          早上好
          {% elif timenow >= 12 and timenow < 14 %}
          中午好
          {% elif timenow >= 14 and timenow < 18 %}
          下午好
          {% elif timenow >= 18 and timenow < 23 %}
          晚上好
          {% else %}
          你好
          {% endif %}
          {{ [
          "现在是{{ now().strftime(\"%H:%M\") }},外面天气{{ states.sensor.caiyun_hourly_skycon.state }},温度{{ states.sensor.caiyun_hourly_temperature.state }},{{ states.sensor.caiyun_minutely_description.state }}",
          "希望你有美好的一天",
          "出门注意安全",
          "我会在家里等你回来的",
          "记得早点回家哦",
          "出门之前想想有没有什么需要带的，有没有辣下的"
          ] | random }}
    - service: notify.weixin
      data_template:
        message: "{{ now().strftime(\"%H:%M\") }}时，有人出门"
        title: "门磁提醒"
