homeassistant:
  sensor:
  - platform: history_stats
    name: jhh at home yesterday
    entity_id: device_tracker.r9s
    state: 'home'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24
   - platform: history_stats
    name: jhh at home last 7 days
    entity_id: device_tracker.r9s
    state: 'home'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      days: 7 
  - platform: history_stats
    name: jhh at bedroom
    entity_id: sensor.jhh
    state: '房间'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24
