telegram_bot:
  - platform: polling
    api_key: ABCDEFGHJKLMNOPQRSTUVXYZ
    allowed_chat_ids:
      - CHAT_ID_1
# Example configuration.yaml entry for the notifier
notify:
  - name: telegram
    platform: telegram
    chat_id: CHAT_ID_2

#If the door has been open for at least 15 minutes, send a notification when it is finally closed
automation: 
  - id: DoorClosed
    alias: Notify when  door is closed after an alert
    trigger:
      platform: state
      entity_id: binary_sensor.menci
      to: 'off'
    action:
      service: notify.telegram
      data:
        message: '{{now().strftime("%H:%M:%S %Y-%m-%d")}}: 门已经关上。' 

#Turn the alert off when a telegram message of /ackGarage is received.       
  - id: replyAckdoor
    alias: 'Telegram bot to ack the Door being open'
    hide_entity: true
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/ackdoor'
    action:
      - service: alert.turn_off
        entity_id: alert.door
      - service: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: '{{ trigger.event.data.id }}'
          message: 'OK'
        
  - id: 'telegrambinsout'
    alias: 'Telegram bot to remind to close the door'
    trigger:
      - entity_id: binary_sensor.menci
        platform: state
        to: 'on'
        for:
          minutes: 30
    action:
      - service: notify.telegram
        data_template:
          message: '现在是{{now().strftime("%H:%M:%S %Y-%m-%d")}}: 门已经打开 {{ relative_time(states.binary_sensor.menci.last_changed) }}'
          data:
            inline_keyboard:
              - '取消提醒:/ackdoor'
              - '不再提醒:/removekeyboard'
  - id: 'telegramremoveinline'
    alias: 'Telegram callback to remove keyboard'
    hide_entity: true
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/removekeyboard'
    action:
      - service: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: '{{ trigger.event.data.id }}'
          message: 'OK'
      - service: telegram_bot.edit_replymarkup
        data_template:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          inline_keyboard: []
#send a repeating alert if the garage door is left open. I put '/ackGarage' at the end of the message to allow the 
#recipient to easily acknowledge it by tapping on it. 
alert:
  door:
    name: '{{now().strftime("%H:%M:%S %Y-%m-%d")}}: 门已经打开 {{ relative_time(states.binary_sensor.menci.last_changed) }}. /ackGarage'
    entity_id: binary_sensor.menci
    state: 'on'  
    repeat:
      - 15
      - 30
    can_acknowledge: True  
    skip_first: True  
    notifiers:
      - telegram
