homeassistant:
# 计时器
timer:
  tvtimer:
    duration: '00:30:00'
# 计数器    
counter:
  counter:
    initial: 0
    step: 1
    name: tv time notify counter
    icon: mdi:counter
# 取消重置按钮
script:
  tvtimer_cancel:
    sequence:
      service: timer.cancel
      entity_id: timer.tvtimer
  timer_pause:
    sequence:
      service: timer.pause
      entity_id: timer.tvtimer
  counter_reset:
    sequence:
      service: counter.reset
      entity_id: counter.counter
  cancel_baned:
    sequence:
      service: shell_command.allowtvbox

automation:
# 电视开机开始启动计时器/重置计数器
  - alias: timer_start
    initial_state: on
    hide_entity: true
    trigger:
      platform: state
      entity_id: device_tracker.tvbox
      to: 'home'
    action:
      - service: counter.reset
        entity_id: counter.counter
      - service: timer.start
        entity_id: timer.tvtimer
  - alias: timer_stop
    initial_state: on
    hide_entity: true
    trigger:
      platform: state
      entity_id: device_tracker.tvbox
      to: 'not_home'
    action:
      - service: timer.cancel
        entity_id: timer.tvtimer
# 时间到，语音提醒--重新计时--计数增加        
  - alias: timer_notify
    initial_state: on
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.tvtimer
    action:
      - service: tts.baidu_say
        entity_id: media_player.media_player.40d4a665be11afecffffffffe14da80f
        data:
          message: >
            {{ [
            "你好，我是电视机，我已经运行半个小时了，好累啊，关机让我休息一下吧", 
            "又半个小时过去了，让你的眼睛休息一下，爱你",
            "半个小时啦，再看爸爸妈妈要生气啦",
            "小朋友要诚实，说好看半个小时就半个小时"
            ] | random }}
      - service: shell_command.banedtvbox
      - delay: "00:{{ (range(0, 30)|random|int) }}:00"
      - service: shell_command.allowtvbox
      - service: tts.baidu_say
        entity_id: media_player.media_player.40d4a665be11afecffffffffe14da80f
        data:
          message: "冻结时间到，又可以看啦“
      - service_template: "{% if states.device_tracker.tvbox.state == 'home' %}timer.start{% else %}timer.canncel{% endif %}"
        entity_id: timer.tvtimer
      - service_template: "{% if states.device_tracker.tvbox.state == 'home' %}counter.increment{% else %}counter.reset{% endif %}"
        entity_id: counter.counter
# 计数达到3次，最后提醒
  - alias: warning
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: counter.counter
        above: 2
        below: 4
        for:
          minutes: 25
    action:
      - service: tts.baidu_say
          entity_id: media_player.media_player.40d4a665be11afecffffffffe14da80f
          data:
            message: '最后警告，最后警告，还有五分钟，请把电视关掉，要不就自动关机了。'
# 到时间关机，重置计数器
  - alias: counter end
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: counter.counter
        above: 3
        below: 5
    action:
      - service: switch.turn_off
        entity_id: switch.tv_switch
      - service: counter.reset
        entity_id: counter.counter
  - alias: turnoff couter end automation
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.firetv
    action:
      service_template: '{% if trigger.to_state.state == "home" %} automation.turn_off {% elif trigger.to_state.state == "not_home" %} automation.turn_on {% endif
%}'
      entity_id: automation.counter_end
  - alias: pause the timer when dlna running
    trigger:
      - platform: state
        entity_id: media_player.40d4a665be11afecffffffffe14da80f
        to: 'playing'
        for:
          minutes: "1"
      - platform: state
        entity_id: media_player.40d4a665be11afecffffffffe14da80f
        to: 'idle'
        for:
          minutes: "5"
    action:
      service_template: '{% if trigger.to_state.state == "playing" %} timer.pause {% elif  trigger.from_state.state == "playing" %} timer.start {% endif %}'
      entity_id: timer.tvtimer
shell_command:
  banedtvbox: '/data/data/com.termux/files/usr/bin/sshpass -p password ssh -o "StrictHostKeyChecking no" -o "PasswordAuthentication yes" admin@192.168.1.1 iptables -I FORWARD -m mac --mac-source 64:88:FF:34:0A:7E -j DROP'
  allowtvbox: '/data/data/com.termux/files/usr/bin/sshpass -p password ssh -o "StrictHostKeyChecking no" -o "PasswordAuthentication yes" admin@192.168.1.1 iptables -I FORWARD -m mac --mac-source 64:88:FF:34:0A:7E -j ACCEPT'
