##############################################################
#                  通过门磁和红外判断厕所是否有人               #
##############################################################
homeassistant:

binary_sensor:
  - platform: template
    sensors:
      temp_and_hum_rise:
        friendly_name: "temp and hum rise when someone washing"
        value_template: >-
           {{ (states.sensor.washroom_temp.state| float - states.sensor.gateway_temp.state| float) | float > 2 and  (states.sensor.washroom_hum.s
tate| float - states.sensor.gateway_hum.state| float)| float > 17}}
  - platform: trend
    sensors:
      hum_falling:
        entity_id: sensor.gateway_hum
        sample_duration: 110
        min_gradient: -0.018 #-2/110
        device_class: moisture

      hum_rising:
        entity_id: sensor.gateway_hum
        sample_duration: 110
        min_gradient: 0.018
        device_class: moisture
        
  - platform: template
    sensors:
      someone_in_washroom:
        friendly_name: "someone washing"
        value_template: >-
          {{ is_state('binary_sensor.csmenci', 'off')
             and is_state('sensor.body_sensor', 'true')}}
          
  - platform: 'bayesian'
    prior: 0.3
    name: 'someone in washroom'
    probability_threshold: 0.95
    observations:
      - entity_id: 'binary_sensor.csmenci'
        prob_given_true: 0.9
        prob_given_false: 0.6
        platform: 'state'
        to_state: 'on'
      - entity_id: 'sensor.body_sensor'
        prob_given_true: 0.95
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'on'
      - entity_id: 'binary_sensor.temp_and_hum_rise'
        prob_given_true: 0.8
        prob_given_false: 0.8
        platform: 'state'
        to_state: 'on'
